config/routes.rb
Mailadmin::Application.routes.draw do
  devise_for :users,:skip => :registrations
  
  match 'sites/public', :to => 'sites#public'
  resources :sites

end

app/models/site.rb
class Site < ActiveRecord::Base
   attr_accessible :name, :address, :login, :pass, :current_client, :current_order, :reg_emails, :orders_emails
   has_many :clients
   has_many :orders
   def import_clients(my_logger)
      load_xml_from_clients(my_logger).select{|cl| cl['id']> current_client }.sort_by{|cl| cl['id']}.each{ |cl|
         field_name_company="Организация"
         field_object_company = cl['fields_values'].select{|fv| fv['name']== field_name_company }.first
         field_name_manager="менеджер"
	 field_object_manager = cl['fields_values'].select{|fv| fv['name']== field_name_manager }.first
         field_name_town="Город"
         field_object_town = cl['fields_values'].select{|fv| fv['name']== field_name_town }.first
	 attrs = {'id' => cl['id'],
                  'name' => cl['name'],
                  'phone' => cl['phone'],
                  'email' => cl['email'],
                  'manager' => field_object_manager ? field_object_manager['value'] : nil ,
		  'company' => field_object_company ? field_object_company['value'] : nil ,
		  'town' => field_object_town ? field_object_town['value'] : nil  }
         cn=clients.new(attrs)
         cn.new_record? ? cn.update_attributes(attrs) : cn.create(attrs)
         self.current_client = cl['id']
         self.save
         my_logger.warn("import_clients +New client:" + cl['id'].to_s)
      }
      return nil
   end
   def import_orders(my_logger)
      load_xml_from_orders(my_logger).select{|od| od['id']> current_order }.sort_by{|od| od['id']}.each{ |od|
         attrs = {'id' => od['id'],
                  'number' => od['number'],
                  'xml' => od.to_xml,
                  'site_id' =>self.id}
         begin
         od=clients.find(od['client']['id']).orders.new(attrs)
         rescue Exception => exc
         	my_logger.warn("Client not found" +exc.message)
         	return nil
         end
         od.new_record? ? od.update_attributes(attrs) : od.create(attrs)
         self.current_order = od['id']
         self.save
         my_logger.warn("import_orders+New order:" + od['id'].to_s)
	 my_logger.warn(od['xml'])

      }
      return nil
   end
   def load_xml_from_clients( my_logger )
      h = []
      require 'net/http'
      i=1
      loop do        
         uri = URI.parse('http://'+address+'/admin/clients.xml?page='+i.to_s)
         my_logger.warn( "load_xml_from "+ uri.to_s )
         r=get_responce_from_insales(uri,my_logger) 
         break if r == nil
         h=h +r['clients']
         i=i+1
      end
      return h
   end
   def load_xml_from_orders( my_logger )
      h = []
      require 'net/http'
      uri = URI.parse('http://'+address+'/admin/orders/orders_by_range.xml?start_order_id='+current_order.to_s+'&limit=2')
      #puts uri
      my_logger.warn( "load_xml_from "+ uri.to_s )
      r=get_responce_from_insales(uri,my_logger)
      
      if r
         h=h +r['orders']
      end

      return h
   end
   
   def check_and_send_emails(ser,my_logger)
      ser.where( "delivered=?",false).each { |se|
      begin
         if se.send_mail(my_logger)
            se.class.to_s
            my_logger.warn( "mail was sent for "+se.class.to_s+" id: "+se.id.to_s )
            se.delivered= true
            se.save
         end
      rescue Net::SMTPFatalError => e
         my_logger.warn("check_and_send_emails")
         my_logger.warn(Time.now)
         my_logger.warn(e.message)
         my_logger.warn(e.to_s)
      end
      }
      return nil
   end
   
   def get_responce_from_insales (uri,my_logger)
      req = Net::HTTP::Get.new(uri.to_s)
      req.basic_auth login, pass
      begin
         response = Net::HTTP.start(uri.host,uri.port ) {|http|
            http.request(req)
            }
      rescue Exception => exc
         my_logger.warn("get_responce_from_insales" +exc.message)
         return nil
      end
      case response
      when Net::HTTPOK
         h=Hash.from_xml(response.body)
         if h["nil_classes"]
            return nil
         else
            return h
         end
      when Net::HTTPClientError, Net::HTTPInternalServerError
         my_logger.warn(response.code + response.message)
         return nil
      end
      
   end
end 
class Client < ActiveRecord::Base
   attr_accessible :id, :name, :company, :town, :manager, :phone, :email, :site_id, :delivered
   belongs_to :site
   has_many :orders
   def send_mail(my_logger)
      Notifier.notify_new_register(self).deliver
   end
end
class Order < ActiveRecord::Base
   attr_accessible :id, :number, :site_id, :client_id, :xml, :delivered
   belongs_to :site
   belongs_to :client
   def send_mail(my_logger)
      Notifier.notify_new_order(self,my_logger).deliver
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!, :except => :public 
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sites }
    end
  end
  def public
    @sites = Site.select("name, address").where("name <>''")
    respond_to do |format|
      format.html # index.html.erb
#	render :json => @sites, :callback => params[:data]
      format.json { render :json => @sites, :callback => params[:callback] }
    end
  end


  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, :notice => 'Site was successfully created.' }
        format.json { render :json => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, :notice => 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mailadmin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="hmenu">
  <%#= render 'devise/shared/links.html' %>
  <%#= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>

<%= yield %>

</body>
</html>

app/views/notifier/notify_new_order.erb
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
<h3>Новый заказ № <%= @order.number %>!</h3>

<p>Организация: <%= @about.company %></p>
<p>Контактное лицо: <%= @about.name %></p>
<p>E-mail: <%= @about.email %></p>
<p>Телефон: <%= @about.phone %></p>


  </body>
</html>

app/views/notifier/notify_new_register.erb
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
<h3>Зарегистрировался новый пользователь!</h3>
<h4>Личные данные:<h4>

<p>Организация: <%= @about.company %></p>
<p>Город: <%= @about.town %></p>
<p>Контактное лицо: <%= @about.name %></p>
<p>Менеджер: <%= @about.manager %></p>
<p>E-mail: <%= @about.email %></p>
<p>Телефон: <%= @about.phone %></p>

  </body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%=f.label :name %><br/>
    <%=f.text_field :name %>
  </div>
  <div class="field">
    <%=f.label :address %><br/>
    <%=f.text_field :address %>
  </div>

  <div class="field">
    <%=f.label :login %><br/>
    <%=f.text_field :login %>
  </div>
  <div class="field">
    <%=f.label :pass %><br/>
    <%=f.text_field :pass %>
  </div>
  <div class="field">
    <%=f.label :current_client %><br/>
    <%=f.text_field :current_client %>
  </div>
  <div class="field">
    <%=f.label :current_order %><br/>
    <%=f.text_field :current_order %>
  </div>
  <div class="field">
    <%=f.label :reg_emails %><br/>
    <%=f.text_field :reg_emails %>
  </div>
  <div class="field">
    <%=f.label :orders_emails %><br/>
    <%=f.text_field :orders_emails %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th>Login</th>
    <th>Password</th>	
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.name %></td>
    <td><%= site.address %></td>
    <td><%= site.login %></td>
    <td><%= site.pass %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @site.name %>
</p>
<p>
  <b>URL:</b>
  <%= @site.address %>
</p>
<p>
  <b>Login:</b>
  <%= @site.login %>
</p>
<p>
  <b>Password:</b>
  <%= @site.pass %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>